final class WritelerCopy {
  const WritelerCopy(this.languageCode);

  final String languageCode;

  static const _de = {
    'appTitle': 'Writeler',
    'projects': 'Projekte',
    'editor': 'Editor',
    'scenes': 'Szenen',
    'chapters': 'Kapitel',
    'characters': 'Figuren',
    'locations': 'Orte',
    'objects': 'Objekte',
    'analysis': 'Analyse',
    'aiWorkshop': 'KI-Werkstatt',
    'exports': 'Export',
    'settings': 'Einstellungen',
    'emptyTitle': 'Noch kein Projekt geoeffnet',
    'emptyBody':
        'Lege ein lokales Schreibprojekt an und strukturiere es in Kapitel, Szenen und Notizen.',
    'newProject': 'Neues Projekt',
    'projectTitle': 'Projekttitel',
    'create': 'Anlegen',
    'cancel': 'Abbrechen',
    'delete': 'Loeschen',
    'deletePermanently': 'Endgueltig loeschen',
    'deleteProject': 'Projekt loeschen',
    'deleteChapter': 'Kapitel loeschen',
    'deleteScene': 'Szene loeschen',
    'deleteCatalogItem': 'Eintrag loeschen',
    'deleteProjectBody':
        'Dieses Projekt und alle lokalen Kapitel, Szenen, Katalogeintraege, Vorschlaege und Metriken werden entfernt.',
    'deleteChapterBody':
        'Das Kapitel wird entfernt. Seine Szenen bleiben erhalten und werden ohne Kapitel einsortiert.',
    'deleteSceneBody':
        'Diese Szene und ihre Kontextverknuepfungen werden entfernt.',
    'deleteCatalogItemBody':
        'Dieser Katalogeintrag und seine Kontextverknuepfungen werden entfernt.',
    'projectDeleted': 'Projekt geloescht',
    'chapterDeleted': 'Kapitel geloescht',
    'sceneDeleted': 'Szene geloescht',
    'catalogItemDeleted': 'Katalogeintrag geloescht',
    'untitledProject': 'Unbenanntes Projekt',
    'localOnly': 'Lokal',
    'projectCreated': 'Projekt angelegt',
    'newScene': 'Neue Szene',
    'newChapter': 'Neues Kapitel',
    'chapter': 'Kapitel',
    'chapterTitle': 'Kapiteltitel',
    'untitledChapter': 'Unbenanntes Kapitel',
    'chapterCreated': 'Kapitel angelegt',
    'noChapter': 'Ohne Kapitel',
    'sceneTitle': 'Szenentitel',
    'untitledScene': 'Unbenannte Szene',
    'sceneCreated': 'Szene angelegt',
    'noScenesTitle': 'Noch keine Szenen',
    'noScenesBody':
        'Lege eine Szene an, um Manuskript, Ziel, Konflikt und Ausgang zu planen.',
    'manuscript': 'Manuskript',
    'saveScene': 'Szene speichern',
    'sceneSaved': 'Szene gespeichert',
    'selectScene': 'Waehle eine Szene aus',
    'words': 'Woerter',
    'characterCount': 'Zeichen',
    'targetProgress': 'Wortziel',
    'focusMode': 'Fokusmodus',
    'exitFocusMode': 'Fokusmodus verlassen',
    'searchReplace': 'Suchen und ersetzen',
    'findText': 'Suchen',
    'replaceWith': 'Ersetzen durch',
    'matches': 'Treffer',
    'nextMatch': 'Naechster Treffer',
    'replaceNext': 'Naechstes ersetzen',
    'replaceAll': 'Alle ersetzen',
    'summary': 'Zusammenfassung',
    'goal': 'Ziel',
    'conflict': 'Konflikt',
    'outcome': 'Ausgang',
    'status': 'Status',
    'wordTarget': 'Wortziel',
    'catalog': 'Katalog',
    'name': 'Name',
    'newCharacter': 'Neue Figur',
    'newLocation': 'Neuer Ort',
    'newObject': 'Neues Objekt',
    'newCatalogItem': 'Neuer Eintrag',
    'untitledCharacter': 'Unbenannte Figur',
    'untitledLocation': 'Unbenannter Ort',
    'untitledObject': 'Unbenanntes Objekt',
    'untitledCatalogItem': 'Unbenannter Eintrag',
    'catalogItemCreated': 'Katalogeintrag angelegt',
    'noCharactersTitle': 'Noch keine Figuren',
    'noLocationsTitle': 'Noch keine Orte',
    'noObjectsTitle': 'Noch keine Objekte',
    'noCatalogItemsTitle': 'Noch keine Eintraege',
    'catalogEmptyBody':
        'Lege Profile an und nutze sie als Kontext fuer Szenen, Analyse und KI-Vorschlaege.',
    'noSummary': 'Keine Zusammenfassung',
    'sceneContext': 'Szenenkontext',
    'sceneContextEmpty':
        'Lege Figuren, Orte oder Objekte an, um sie mit dieser Szene zu verknuepfen.',
    'relationships': 'Verknuepfungen',
    'openSuggestions': 'Offene Vorschlaege',
    'metricEvents': 'Lokale Events',
    'todaySaves': 'Speicherungen heute',
    'aiUses': 'KI-Nutzung',
    'recentMetrics': 'Letzte lokale Ereignisse',
    'noMetricsYet': 'Noch keine lokalen Metriken fuer dieses Projekt.',
    'recentScenes': 'Aktuelle Szenen',
    'sceneBoard': 'Szenenboard',
    'structureCockpit': 'Struktur-Cockpit',
    'planningGaps': 'Planungsluecken',
    'unassignedScenes': 'Ohne Kapitel',
    'timeline': 'Timeline',
    'unscheduled': 'Ohne Datum',
    'statusSpread': 'Statusverteilung',
    'datedScenes': 'Datierte Szenen',
    'chapterOverview': 'Kapitelueberblick',
    'storyAnalysis': 'Storyline & Analyse',
    'storylineHealth': 'Storyline-Pruefung',
    'chapterBalance': 'Kapitelbalance',
    'catalogPresence': 'Praesenzmatrix',
    'openPlanningGaps': 'Offene Planungsluecken',
    'scenesWithoutPov': 'Szenen ohne Perspektive',
    'scenesWithoutDate': 'Szenen ohne Datum',
    'detachedCatalogItems': 'Eintraege ohne Auftritt',
    'missingStructure': 'Ziel, Konflikt oder Ausgang fehlt',
    'noAnalysisIssues': 'Keine akuten Strukturhinweise.',
    'noAppearances': 'Keine Auftritte',
    'appearances': 'Auftritte',
    'linkedScenes': 'Verknuepfte Szenen',
    'wordsPerChapter': 'Woerter pro Kapitel',
    'structureActions': 'Strukturaktionen',
    'moveSceneUp': 'Szene nach oben',
    'moveSceneDown': 'Szene nach unten',
    'moveToChapter': 'In Kapitel verschieben',
    'moveToNoChapter': 'Ohne Kapitel',
    'aiNeedsScene':
        'Lege zuerst eine Szene an, bevor KI-Vorschlaege erzeugt werden.',
    'aiContext': 'Kontext',
    'aiPrompt': 'Auftrag an die KI',
    'defaultAiPrompt':
        'Pruefe diese Szene und schlage strukturierende Fragen vor.',
    'requestSceneIdeas': 'Szenenideen',
    'requestStructure': 'Ziel/Konflikt/Ausgang',
    'moreAiChecks': 'Weitere Pruefungen',
    'submitAiPrompt': 'Auftrag senden',
    'aiPromptSubmitHint': 'Strg+Enter sendet den Auftrag',
    'aiApiKeyMissing':
        'Fuer diesen Provider ist ein API-Key noetig. Speichere ihn unter Einstellungen > Provider-Konfiguration.',
    'aiRequestInProgress': 'Provider-Anfrage laeuft...',
    'aiRequestFailed': 'Provider-Anfrage fehlgeschlagen',
    'aiSuggestionCreated': 'KI-Vorschlag gespeichert',
    'aiMockProviderActive':
        'Mock / lokal ist aktiv - Antworten sind Demo-Platzhalter. Speichere OpenRouter oder einen anderen Provider in den Einstellungen.',
    'aiTaskCustomScenePrompt': 'Eigener KI-Auftrag',
    'aiTaskCharacterProfile': 'Figurenprofil',
    'aiTaskConsistencyCheck': 'Konsistenzpruefung',
    'aiTaskTimelineCheck': 'Timeline-Pruefung',
    'aiTaskStorylineVariants': 'Storyline-Varianten',
    'aiTaskBlurbVariants': 'Klappentext-Varianten',
    'aiTaskStyleAnalysis': 'Stilanalyse',
    'aiTaskAuthorQuestions': 'Autorenfragen',
    'aiTaskResearchStructuring': 'Recherche strukturieren',
    'aiTaskPlotGapReview': 'Plot-Luecken pruefen',
    'aiTaskDialogueIntentAnalysis': 'Dialogabsicht analysieren',
    'suggestions': 'Vorschlaege',
    'noSuggestions': 'Noch keine Vorschlaege',
    'notes': 'Notizen',
    'noNotes': 'Noch keine Notizen',
    'noteDeleted': 'Notiz geloescht',
    'aiResponse': 'Antwort',
    'sentPrompt': 'Gesendeter Prompt',
    'suggestionPending': 'offen',
    'suggestionAccepted': 'angenommen',
    'suggestionRejected': 'abgelehnt',
    'suggestionConverted': 'als Notiz gesichert',
    'suggestionAcceptedFeedback': 'Vorschlag angenommen',
    'suggestionDeletedFeedback': 'Vorschlag geloescht',
    'suggestionConvertedFeedback': 'Notiz aus Vorschlag erstellt',
    'accept': 'Annehmen',
    'reject': 'Ablehnen',
    'convertToNote': 'Als Notiz markieren',
    'exportPreview': 'Exportvorschau',
    'copyExport': 'Export kopieren',
    'downloadExport': 'Export herunterladen',
    'exportCopied': 'Export in die Zwischenablage kopiert',
    'exportDownloaded': 'Export heruntergeladen',
    'syncCheckpoint': 'Sync-Checkpoint',
    'syncCheckpointBody':
        'Erzeugt ein vollstaendiges, lokales Sync-Paket fuer manuelle Ablage, WebDAV oder spaetere Cloud-Adapter.',
    'copySyncCheckpoint': 'Sync-Checkpoint kopieren',
    'syncCheckpointCopied': 'Sync-Checkpoint in die Zwischenablage kopiert',
    'lastSyncCheckpoint': 'Letzter Checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Paketgroesse',
    'syncPayloadDetected': 'Sync-Paket erkannt',
    'syncAdapter': 'Sync-Adapter',
    'syncAdapterHint':
        'Lokale Nutzung bleibt unabhaengig; Cloud-Sync ist nur ein optionaler Adapter.',
    'importArchive': 'Projektarchiv importieren',
    'archiveSchema': 'Archivschema',
    'archivePreviewInvalid': 'Archivvorschau nicht moeglich',
    'pasteArchiveJson': 'Writeler-JSON hier einfuegen',
    'importProject': 'Projekt importieren',
    'importComplete': 'Projektarchiv importiert',
    'format': 'Format',
    'includeSceneTitles': 'Szenentitel einschliessen',
    'includeMetadata': 'Metadaten einschliessen',
    'nothingToExport': 'Noch nichts zu exportieren',
    'selectProject': 'Waehle ein Projekt aus',
    'aiEnabled': 'KI-Unterstuetzung',
    'cloudSyncEnabled': 'Cloud-Sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider-Konfiguration',
    'providerKind': 'Provider-Typ',
    'providerEnabled': 'Provider aktiv',
    'providerName': 'Providername',
    'modelName': 'Modellname',
    'baseUrl': 'Base-URL',
    'apiKeyRef': 'API-Key',
    'apiKeyWebWarning':
        'Wird getrennt von der Provider-Konfiguration sicher lokal gespeichert.',
    'apiKeyStoredHint':
        'API-Key ist sicher gespeichert. Leer lassen, um ihn beizubehalten.',
    'deleteApiKey': 'API-Key entfernen',
    'apiKeyDeleted': 'API-Key entfernt',
    'saveProviderConfig': 'Provider speichern',
    'providerConfigSaved': 'Provider-Konfiguration gespeichert',
    'activeProvider': 'Aktiver Provider',
    'providerNameFallback': 'Lokaler Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  static const _en = {
    'appTitle': 'Writeler',
    'projects': 'Projects',
    'editor': 'Editor',
    'scenes': 'Scenes',
    'chapters': 'Chapters',
    'characterCount': 'Characters',
    'locations': 'Locations',
    'objects': 'Objects',
    'analysis': 'Analysis',
    'aiWorkshop': 'AI Workshop',
    'exports': 'Export',
    'settings': 'Settings',
    'emptyTitle': 'No project open',
    'emptyBody':
        'Create a local writing project and organize it into chapters, scenes, and notes.',
    'newProject': 'New Project',
    'projectTitle': 'Project title',
    'create': 'Create',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'deletePermanently': 'Delete permanently',
    'deleteProject': 'Delete project',
    'deleteChapter': 'Delete chapter',
    'deleteScene': 'Delete scene',
    'deleteCatalogItem': 'Delete entry',
    'deleteProjectBody':
        'This project and all local chapters, scenes, catalog entries, suggestions, and metrics will be removed.',
    'deleteChapterBody':
        'The chapter will be removed. Its scenes stay available and move to no chapter.',
    'deleteSceneBody': 'This scene and its context links will be removed.',
    'deleteCatalogItemBody':
        'This catalog entry and its context links will be removed.',
    'projectDeleted': 'Project deleted',
    'chapterDeleted': 'Chapter deleted',
    'sceneDeleted': 'Scene deleted',
    'catalogItemDeleted': 'Catalog item deleted',
    'untitledProject': 'Untitled Project',
    'localOnly': 'Local',
    'projectCreated': 'Project created',
    'newScene': 'New Scene',
    'newChapter': 'New Chapter',
    'chapter': 'Chapter',
    'chapterTitle': 'Chapter title',
    'untitledChapter': 'Untitled Chapter',
    'chapterCreated': 'Chapter created',
    'noChapter': 'No chapter',
    'sceneTitle': 'Scene title',
    'untitledScene': 'Untitled Scene',
    'sceneCreated': 'Scene created',
    'noScenesTitle': 'No scenes yet',
    'noScenesBody':
        'Create a scene to plan manuscript, goal, conflict, and outcome.',
    'manuscript': 'Manuscript',
    'saveScene': 'Save Scene',
    'sceneSaved': 'Scene saved',
    'selectScene': 'Select a scene',
    'words': 'words',
    'characters': 'Characters',
    'targetProgress': 'Word target',
    'focusMode': 'Focus mode',
    'exitFocusMode': 'Exit focus mode',
    'searchReplace': 'Find and replace',
    'findText': 'Find',
    'replaceWith': 'Replace with',
    'matches': 'Matches',
    'nextMatch': 'Next match',
    'replaceNext': 'Replace next',
    'replaceAll': 'Replace all',
    'summary': 'Summary',
    'goal': 'Goal',
    'conflict': 'Conflict',
    'outcome': 'Outcome',
    'status': 'Status',
    'wordTarget': 'Word target',
    'catalog': 'Catalog',
    'name': 'Name',
    'newCharacter': 'New Character',
    'newLocation': 'New Location',
    'newObject': 'New Object',
    'newCatalogItem': 'New Entry',
    'untitledCharacter': 'Untitled Character',
    'untitledLocation': 'Untitled Location',
    'untitledObject': 'Untitled Object',
    'untitledCatalogItem': 'Untitled Entry',
    'catalogItemCreated': 'Catalog item created',
    'noCharactersTitle': 'No characters yet',
    'noLocationsTitle': 'No locations yet',
    'noObjectsTitle': 'No objects yet',
    'noCatalogItemsTitle': 'No entries yet',
    'catalogEmptyBody':
        'Create profiles and use them as context for scenes, analysis, and AI suggestions.',
    'noSummary': 'No summary',
    'sceneContext': 'Scene context',
    'sceneContextEmpty':
        'Create characters, locations, or objects to link them with this scene.',
    'relationships': 'Relationships',
    'openSuggestions': 'Open suggestions',
    'metricEvents': 'Local events',
    'todaySaves': 'Saves today',
    'aiUses': 'AI usage',
    'recentMetrics': 'Recent local events',
    'noMetricsYet': 'No local metrics for this project yet.',
    'recentScenes': 'Recent scenes',
    'sceneBoard': 'Scene board',
    'structureCockpit': 'Structure cockpit',
    'planningGaps': 'Planning gaps',
    'unassignedScenes': 'No chapter',
    'timeline': 'Timeline',
    'unscheduled': 'Unscheduled',
    'statusSpread': 'Status spread',
    'datedScenes': 'Dated scenes',
    'chapterOverview': 'Chapter overview',
    'storyAnalysis': 'Storyline & Analysis',
    'storylineHealth': 'Storyline health',
    'chapterBalance': 'Chapter balance',
    'catalogPresence': 'Presence matrix',
    'openPlanningGaps': 'Open planning gaps',
    'scenesWithoutPov': 'Scenes without POV',
    'scenesWithoutDate': 'Scenes without date',
    'detachedCatalogItems': 'Entries without appearance',
    'missingStructure': 'Goal, conflict, or outcome is missing',
    'noAnalysisIssues': 'No immediate structure notes.',
    'noAppearances': 'No appearances',
    'appearances': 'Appearances',
    'linkedScenes': 'Linked scenes',
    'wordsPerChapter': 'Words per chapter',
    'structureActions': 'Structure actions',
    'moveSceneUp': 'Move scene up',
    'moveSceneDown': 'Move scene down',
    'moveToChapter': 'Move to chapter',
    'moveToNoChapter': 'No chapter',
    'aiNeedsScene': 'Create a scene before requesting AI suggestions.',
    'aiContext': 'Context',
    'aiPrompt': 'AI task',
    'defaultAiPrompt': 'Review this scene and suggest structuring questions.',
    'requestSceneIdeas': 'Scene ideas',
    'requestStructure': 'Goal/conflict/outcome',
    'moreAiChecks': 'More checks',
    'submitAiPrompt': 'Send task',
    'aiPromptSubmitHint': 'Ctrl+Enter sends the task',
    'aiApiKeyMissing':
        'This provider needs an API key. Save it under Settings > Provider configuration.',
    'aiRequestInProgress': 'Provider request in progress...',
    'aiRequestFailed': 'Provider request failed',
    'aiSuggestionCreated': 'AI suggestion saved',
    'aiMockProviderActive':
        'Mock / local is active - responses are demo placeholders. Save OpenRouter or another provider in Settings.',
    'aiTaskCustomScenePrompt': 'Custom AI task',
    'aiTaskCharacterProfile': 'Character profile',
    'aiTaskConsistencyCheck': 'Consistency check',
    'aiTaskTimelineCheck': 'Timeline check',
    'aiTaskStorylineVariants': 'Storyline variants',
    'aiTaskBlurbVariants': 'Blurb variants',
    'aiTaskStyleAnalysis': 'Style analysis',
    'aiTaskAuthorQuestions': 'Author questions',
    'aiTaskResearchStructuring': 'Research structuring',
    'aiTaskPlotGapReview': 'Plot gap review',
    'aiTaskDialogueIntentAnalysis': 'Dialogue intent analysis',
    'suggestions': 'Suggestions',
    'noSuggestions': 'No suggestions yet',
    'notes': 'Notes',
    'noNotes': 'No notes yet',
    'noteDeleted': 'Note deleted',
    'aiResponse': 'Response',
    'sentPrompt': 'Sent prompt',
    'suggestionPending': 'pending',
    'suggestionAccepted': 'accepted',
    'suggestionRejected': 'rejected',
    'suggestionConverted': 'saved as note',
    'suggestionAcceptedFeedback': 'Suggestion accepted',
    'suggestionDeletedFeedback': 'Suggestion deleted',
    'suggestionConvertedFeedback': 'Note created from suggestion',
    'accept': 'Accept',
    'reject': 'Reject',
    'convertToNote': 'Mark as note',
    'exportPreview': 'Export preview',
    'copyExport': 'Copy export',
    'downloadExport': 'Download export',
    'exportCopied': 'Export copied to clipboard',
    'exportDownloaded': 'Export downloaded',
    'syncCheckpoint': 'Sync checkpoint',
    'syncCheckpointBody':
        'Creates a complete local sync package for manual storage, WebDAV, or future cloud adapters.',
    'copySyncCheckpoint': 'Copy sync checkpoint',
    'syncCheckpointCopied': 'Sync checkpoint copied to clipboard',
    'lastSyncCheckpoint': 'Last checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Payload size',
    'syncPayloadDetected': 'Sync package detected',
    'syncAdapter': 'Sync adapter',
    'syncAdapterHint':
        'Local use remains independent; cloud sync is only an optional adapter.',
    'importArchive': 'Import project archive',
    'archiveSchema': 'Archive schema',
    'archivePreviewInvalid': 'Archive preview unavailable',
    'pasteArchiveJson': 'Paste Writeler JSON here',
    'importProject': 'Import project',
    'importComplete': 'Project archive imported',
    'format': 'Format',
    'includeSceneTitles': 'Include scene titles',
    'includeMetadata': 'Include metadata',
    'nothingToExport': 'Nothing to export yet',
    'selectProject': 'Select a project',
    'aiEnabled': 'AI assistance',
    'cloudSyncEnabled': 'Cloud sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider configuration',
    'providerKind': 'Provider type',
    'providerEnabled': 'Provider enabled',
    'providerName': 'Provider name',
    'modelName': 'Model name',
    'baseUrl': 'Base URL',
    'apiKeyRef': 'API key',
    'apiKeyWebWarning':
        'Stored locally in secure storage, separate from provider configuration.',
    'apiKeyStoredHint': 'API key is securely stored. Leave blank to keep it.',
    'deleteApiKey': 'Delete API key',
    'apiKeyDeleted': 'API key deleted',
    'saveProviderConfig': 'Save provider',
    'providerConfigSaved': 'Provider configuration saved',
    'activeProvider': 'Active provider',
    'providerNameFallback': 'Local Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  String t(String key) {
    final table = languageCode == 'de' ? _de : _en;
    return table[key] ?? _en[key] ?? key;
  }
}
