final class WritelerCopy {
  const WritelerCopy(this.languageCode);

  final String languageCode;

  static const _de = {
    'appTitle': 'Writeler',
    'projects': 'Projekte',
    'editor': 'Editor',
    'scenes': 'Szenen',
    'chapters': 'Kapitel',
    'characters': 'Figuren',
    'locations': 'Orte',
    'objects': 'Objekte',
    'aiWorkshop': 'KI-Werkstatt',
    'exports': 'Export',
    'settings': 'Einstellungen',
    'emptyTitle': 'Noch kein Projekt geoeffnet',
    'emptyBody':
        'Lege ein lokales Schreibprojekt an und strukturiere es in Kapitel, Szenen und Notizen.',
    'newProject': 'Neues Projekt',
    'projectTitle': 'Projekttitel',
    'create': 'Anlegen',
    'cancel': 'Abbrechen',
    'untitledProject': 'Unbenanntes Projekt',
    'localOnly': 'Lokal',
    'projectCreated': 'Projekt angelegt',
    'newScene': 'Neue Szene',
    'newChapter': 'Neues Kapitel',
    'chapter': 'Kapitel',
    'chapterTitle': 'Kapiteltitel',
    'untitledChapter': 'Unbenanntes Kapitel',
    'chapterCreated': 'Kapitel angelegt',
    'noChapter': 'Ohne Kapitel',
    'sceneTitle': 'Szenentitel',
    'untitledScene': 'Unbenannte Szene',
    'sceneCreated': 'Szene angelegt',
    'noScenesTitle': 'Noch keine Szenen',
    'noScenesBody':
        'Lege eine Szene an, um Manuskript, Ziel, Konflikt und Ausgang zu planen.',
    'manuscript': 'Manuskript',
    'saveScene': 'Szene speichern',
    'sceneSaved': 'Szene gespeichert',
    'selectScene': 'Waehle eine Szene aus',
    'words': 'Woerter',
    'characterCount': 'Zeichen',
    'targetProgress': 'Wortziel',
    'focusMode': 'Fokusmodus',
    'exitFocusMode': 'Fokusmodus verlassen',
    'searchReplace': 'Suchen und ersetzen',
    'findText': 'Suchen',
    'replaceWith': 'Ersetzen durch',
    'matches': 'Treffer',
    'nextMatch': 'Naechster Treffer',
    'replaceNext': 'Naechstes ersetzen',
    'replaceAll': 'Alle ersetzen',
    'summary': 'Zusammenfassung',
    'goal': 'Ziel',
    'conflict': 'Konflikt',
    'outcome': 'Ausgang',
    'status': 'Status',
    'wordTarget': 'Wortziel',
    'catalog': 'Katalog',
    'name': 'Name',
    'newCharacter': 'Neue Figur',
    'newLocation': 'Neuer Ort',
    'newObject': 'Neues Objekt',
    'newCatalogItem': 'Neuer Eintrag',
    'untitledCharacter': 'Unbenannte Figur',
    'untitledLocation': 'Unbenannter Ort',
    'untitledObject': 'Unbenanntes Objekt',
    'untitledCatalogItem': 'Unbenannter Eintrag',
    'catalogItemCreated': 'Katalogeintrag angelegt',
    'noCharactersTitle': 'Noch keine Figuren',
    'noLocationsTitle': 'Noch keine Orte',
    'noObjectsTitle': 'Noch keine Objekte',
    'noCatalogItemsTitle': 'Noch keine Eintraege',
    'catalogEmptyBody':
        'Lege Profile an und nutze sie als Kontext fuer Szenen, Analyse und KI-Vorschlaege.',
    'noSummary': 'Keine Zusammenfassung',
    'sceneContext': 'Szenenkontext',
    'sceneContextEmpty':
        'Lege Figuren, Orte oder Objekte an, um sie mit dieser Szene zu verknuepfen.',
    'relationships': 'Verknuepfungen',
    'openSuggestions': 'Offene Vorschlaege',
    'metricEvents': 'Lokale Events',
    'todaySaves': 'Speicherungen heute',
    'aiUses': 'KI-Nutzung',
    'recentMetrics': 'Letzte lokale Ereignisse',
    'noMetricsYet': 'Noch keine lokalen Metriken fuer dieses Projekt.',
    'recentScenes': 'Aktuelle Szenen',
    'sceneBoard': 'Szenenboard',
    'structureActions': 'Strukturaktionen',
    'moveSceneUp': 'Szene nach oben',
    'moveSceneDown': 'Szene nach unten',
    'moveToChapter': 'In Kapitel verschieben',
    'moveToNoChapter': 'Ohne Kapitel',
    'aiNeedsScene':
        'Lege zuerst eine Szene an, bevor KI-Vorschlaege erzeugt werden.',
    'aiContext': 'Kontext',
    'aiPrompt': 'Auftrag an die KI',
    'defaultAiPrompt':
        'Pruefe diese Szene und schlage strukturierende Fragen vor.',
    'requestSceneIdeas': 'Szenenideen',
    'requestStructure': 'Ziel/Konflikt/Ausgang',
    'aiRequestInProgress': 'Provider-Anfrage laeuft...',
    'aiRequestFailed': 'Provider-Anfrage fehlgeschlagen',
    'aiSuggestionCreated': 'KI-Vorschlag gespeichert',
    'suggestions': 'Vorschlaege',
    'noSuggestions': 'Noch keine Vorschlaege',
    'accept': 'Annehmen',
    'reject': 'Ablehnen',
    'convertToNote': 'Als Notiz markieren',
    'exportPreview': 'Exportvorschau',
    'copyExport': 'Export kopieren',
    'downloadExport': 'Export herunterladen',
    'exportCopied': 'Export in die Zwischenablage kopiert',
    'exportDownloaded': 'Export heruntergeladen',
    'syncCheckpoint': 'Sync-Checkpoint',
    'syncCheckpointBody':
        'Erzeugt ein vollstaendiges, lokales Sync-Paket fuer manuelle Ablage, WebDAV oder spaetere Cloud-Adapter.',
    'copySyncCheckpoint': 'Sync-Checkpoint kopieren',
    'syncCheckpointCopied': 'Sync-Checkpoint in die Zwischenablage kopiert',
    'lastSyncCheckpoint': 'Letzter Checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Paketgroesse',
    'syncPayloadDetected': 'Sync-Paket erkannt',
    'syncAdapter': 'Sync-Adapter',
    'syncAdapterHint':
        'Lokale Nutzung bleibt unabhaengig; Cloud-Sync ist nur ein optionaler Adapter.',
    'importArchive': 'Projektarchiv importieren',
    'archiveSchema': 'Archivschema',
    'archivePreviewInvalid': 'Archivvorschau nicht moeglich',
    'pasteArchiveJson': 'Writeler-JSON hier einfuegen',
    'importProject': 'Projekt importieren',
    'importComplete': 'Projektarchiv importiert',
    'format': 'Format',
    'includeSceneTitles': 'Szenentitel einschliessen',
    'includeMetadata': 'Metadaten einschliessen',
    'nothingToExport': 'Noch nichts zu exportieren',
    'selectProject': 'Waehle ein Projekt aus',
    'aiEnabled': 'KI-Unterstuetzung',
    'cloudSyncEnabled': 'Cloud-Sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider-Konfiguration',
    'providerKind': 'Provider-Typ',
    'providerEnabled': 'Provider aktiv',
    'providerName': 'Providername',
    'modelName': 'Modellname',
    'baseUrl': 'Base-URL',
    'apiKeyRef': 'API-Key',
    'apiKeyWebWarning':
        'Wird getrennt von der Provider-Konfiguration sicher lokal gespeichert.',
    'apiKeyStoredHint':
        'API-Key ist sicher gespeichert. Leer lassen, um ihn beizubehalten.',
    'deleteApiKey': 'API-Key entfernen',
    'apiKeyDeleted': 'API-Key entfernt',
    'saveProviderConfig': 'Provider speichern',
    'providerConfigSaved': 'Provider-Konfiguration gespeichert',
    'activeProvider': 'Aktiver Provider',
    'providerNameFallback': 'Lokaler Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  static const _en = {
    'appTitle': 'Writeler',
    'projects': 'Projects',
    'editor': 'Editor',
    'scenes': 'Scenes',
    'chapters': 'Chapters',
    'characterCount': 'Characters',
    'locations': 'Locations',
    'objects': 'Objects',
    'aiWorkshop': 'AI Workshop',
    'exports': 'Export',
    'settings': 'Settings',
    'emptyTitle': 'No project open',
    'emptyBody':
        'Create a local writing project and organize it into chapters, scenes, and notes.',
    'newProject': 'New Project',
    'projectTitle': 'Project title',
    'create': 'Create',
    'cancel': 'Cancel',
    'untitledProject': 'Untitled Project',
    'localOnly': 'Local',
    'projectCreated': 'Project created',
    'newScene': 'New Scene',
    'newChapter': 'New Chapter',
    'chapter': 'Chapter',
    'chapterTitle': 'Chapter title',
    'untitledChapter': 'Untitled Chapter',
    'chapterCreated': 'Chapter created',
    'noChapter': 'No chapter',
    'sceneTitle': 'Scene title',
    'untitledScene': 'Untitled Scene',
    'sceneCreated': 'Scene created',
    'noScenesTitle': 'No scenes yet',
    'noScenesBody':
        'Create a scene to plan manuscript, goal, conflict, and outcome.',
    'manuscript': 'Manuscript',
    'saveScene': 'Save Scene',
    'sceneSaved': 'Scene saved',
    'selectScene': 'Select a scene',
    'words': 'words',
    'characters': 'Characters',
    'targetProgress': 'Word target',
    'focusMode': 'Focus mode',
    'exitFocusMode': 'Exit focus mode',
    'searchReplace': 'Find and replace',
    'findText': 'Find',
    'replaceWith': 'Replace with',
    'matches': 'Matches',
    'nextMatch': 'Next match',
    'replaceNext': 'Replace next',
    'replaceAll': 'Replace all',
    'summary': 'Summary',
    'goal': 'Goal',
    'conflict': 'Conflict',
    'outcome': 'Outcome',
    'status': 'Status',
    'wordTarget': 'Word target',
    'catalog': 'Catalog',
    'name': 'Name',
    'newCharacter': 'New Character',
    'newLocation': 'New Location',
    'newObject': 'New Object',
    'newCatalogItem': 'New Entry',
    'untitledCharacter': 'Untitled Character',
    'untitledLocation': 'Untitled Location',
    'untitledObject': 'Untitled Object',
    'untitledCatalogItem': 'Untitled Entry',
    'catalogItemCreated': 'Catalog item created',
    'noCharactersTitle': 'No characters yet',
    'noLocationsTitle': 'No locations yet',
    'noObjectsTitle': 'No objects yet',
    'noCatalogItemsTitle': 'No entries yet',
    'catalogEmptyBody':
        'Create profiles and use them as context for scenes, analysis, and AI suggestions.',
    'noSummary': 'No summary',
    'sceneContext': 'Scene context',
    'sceneContextEmpty':
        'Create characters, locations, or objects to link them with this scene.',
    'relationships': 'Relationships',
    'openSuggestions': 'Open suggestions',
    'metricEvents': 'Local events',
    'todaySaves': 'Saves today',
    'aiUses': 'AI usage',
    'recentMetrics': 'Recent local events',
    'noMetricsYet': 'No local metrics for this project yet.',
    'recentScenes': 'Recent scenes',
    'sceneBoard': 'Scene board',
    'structureActions': 'Structure actions',
    'moveSceneUp': 'Move scene up',
    'moveSceneDown': 'Move scene down',
    'moveToChapter': 'Move to chapter',
    'moveToNoChapter': 'No chapter',
    'aiNeedsScene': 'Create a scene before requesting AI suggestions.',
    'aiContext': 'Context',
    'aiPrompt': 'AI task',
    'defaultAiPrompt': 'Review this scene and suggest structuring questions.',
    'requestSceneIdeas': 'Scene ideas',
    'requestStructure': 'Goal/conflict/outcome',
    'aiRequestInProgress': 'Provider request in progress...',
    'aiRequestFailed': 'Provider request failed',
    'aiSuggestionCreated': 'AI suggestion saved',
    'suggestions': 'Suggestions',
    'noSuggestions': 'No suggestions yet',
    'accept': 'Accept',
    'reject': 'Reject',
    'convertToNote': 'Mark as note',
    'exportPreview': 'Export preview',
    'copyExport': 'Copy export',
    'downloadExport': 'Download export',
    'exportCopied': 'Export copied to clipboard',
    'exportDownloaded': 'Export downloaded',
    'syncCheckpoint': 'Sync checkpoint',
    'syncCheckpointBody':
        'Creates a complete local sync package for manual storage, WebDAV, or future cloud adapters.',
    'copySyncCheckpoint': 'Copy sync checkpoint',
    'syncCheckpointCopied': 'Sync checkpoint copied to clipboard',
    'lastSyncCheckpoint': 'Last checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Payload size',
    'syncPayloadDetected': 'Sync package detected',
    'syncAdapter': 'Sync adapter',
    'syncAdapterHint':
        'Local use remains independent; cloud sync is only an optional adapter.',
    'importArchive': 'Import project archive',
    'archiveSchema': 'Archive schema',
    'archivePreviewInvalid': 'Archive preview unavailable',
    'pasteArchiveJson': 'Paste Writeler JSON here',
    'importProject': 'Import project',
    'importComplete': 'Project archive imported',
    'format': 'Format',
    'includeSceneTitles': 'Include scene titles',
    'includeMetadata': 'Include metadata',
    'nothingToExport': 'Nothing to export yet',
    'selectProject': 'Select a project',
    'aiEnabled': 'AI assistance',
    'cloudSyncEnabled': 'Cloud sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider configuration',
    'providerKind': 'Provider type',
    'providerEnabled': 'Provider enabled',
    'providerName': 'Provider name',
    'modelName': 'Model name',
    'baseUrl': 'Base URL',
    'apiKeyRef': 'API key',
    'apiKeyWebWarning':
        'Stored locally in secure storage, separate from provider configuration.',
    'apiKeyStoredHint': 'API key is securely stored. Leave blank to keep it.',
    'deleteApiKey': 'Delete API key',
    'apiKeyDeleted': 'API key deleted',
    'saveProviderConfig': 'Save provider',
    'providerConfigSaved': 'Provider configuration saved',
    'activeProvider': 'Active provider',
    'providerNameFallback': 'Local Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  String t(String key) {
    final table = languageCode == 'de' ? _de : _en;
    return table[key] ?? _en[key] ?? key;
  }
}
