final class WritelerCopy {
  const WritelerCopy(this.languageCode);

  final String languageCode;

  static const _de = {
    'appTitle': 'Writeler',
    'dashboard': 'Dashboard',
    'projects': 'Projekte',
    'project': 'Projekt',
    'editor': 'Editor',
    'scenes': 'Szenen',
    'scene': 'Szene',
    'chapters': 'Kapitel',
    'characters': 'Figuren',
    'character': 'Figur',
    'locations': 'Orte',
    'location': 'Ort',
    'objects': 'Objekte',
    'object': 'Objekt',
    'analysis': 'Analyse',
    'aiWorkshop': 'KI-Werkstatt',
    'exports': 'Export',
    'settings': 'Einstellungen',
    'designSettings': 'Design',
    'designSettingsBody':
        'Wähle die Arbeitsstimmung für Oberfläche, Marke und Fokusflächen.',
    'designThemePaper': 'Hell',
    'designThemeDusk': 'Dunkel',
    'designThemeSapphire': 'Saphir',
    'designThemeSage': 'Salbei',
    'designThemeCopper': 'Kupfer',
    'designThemeInk': 'Tinte',
    'privacySettings': 'Projekt & Privatsphäre',
    'privacySettingsBody':
        'Steuert, wie dieses Projekt KI und optionale Synchronisation nutzt.',
    'providerSettingsBody':
        'Provider, Modell und API-Key für KI-Funktionen konfigurieren.',
    'emptyTitle': 'Noch kein Projekt geöffnet',
    'emptyBody':
        'Lege ein lokales Schreibprojekt an und strukturiere es in Kapitel, Szenen und Notizen.',
    'dashboardBody':
        'Projektstatus, offene Strukturpunkte und nächste Arbeitsschritte an einem Ort.',
    'openEditor': 'Editor öffnen',
    'projectPulse': 'Projektpuls',
    'nextActions': 'Nächste Schritte',
    'nextActionsBody':
        'Direkte Wege zu den Stellen, die gerade Aufmerksamkeit brauchen.',
    'continueWriting': 'Weiterschreiben',
    'reviewStructure': 'Struktur prüfen',
    'reviewSuggestions': 'KI-Vorschläge prüfen',
    'reviewNotes': 'Notizen sichten',
    'nextSceneWithoutText': 'Nächste Szene ohne Text',
    'mostUrgentPlanningGap': 'Dringendste Planungslücke',
    'latestOpenAiResponse': 'Letzte KI-Antwort offen',
    'noteWithoutTarget': 'Notiz ohne Ziel',
    'noDashboardActions': 'Keine dringenden nächsten Schritte.',
    'structureFocus': 'Strukturstatus',
    'structureFocusBody':
        'Planung, Zuordnung und Katalogbindung für das aktuelle Projekt.',
    'emptyDraftScenes': 'Szenen ohne Manuskript',
    'recentScenesBody':
        'Zuletzt bearbeitete Szenen mit Wortstand und Planungsstatus.',
    'noRecentScenes': 'Noch keine Szenen im Projekt.',
    'activityStream': 'Aktivität',
    'activityStreamBody': 'Lokale Ereignisse aus Schreiben, KI und Export.',
    'noActivityYet': 'Noch keine Aktivität für dieses Projekt.',
    'dashboardSignals': 'Signale',
    'dashboardSignalsBody':
        'Kurzstatus für KI, Notizen und heutige Schreibarbeit.',
    'aiQueue': 'KI-Warteschlange',
    'notesQueue': 'Notizen',
    'newProject': 'Neues Projekt',
    'projectTitle': 'Projekttitel',
    'create': 'Anlegen',
    'cancel': 'Abbrechen',
    'delete': 'Löschen',
    'deletePermanently': 'Endgültig löschen',
    'deleteProject': 'Projekt löschen',
    'deleteChapter': 'Kapitel löschen',
    'deleteScene': 'Szene löschen',
    'deleteCatalogItem': 'Eintrag löschen',
    'deleteProjectBody':
        'Dieses Projekt und alle lokalen Kapitel, Szenen, Katalogeinträge, Vorschläge und Metriken werden entfernt.',
    'deleteChapterBody':
        'Das Kapitel wird entfernt. Seine Szenen bleiben erhalten und werden ohne Kapitel einsortiert.',
    'deleteSceneBody':
        'Diese Szene und ihre Kontextverknüpfungen werden entfernt.',
    'deleteCatalogItemBody':
        'Dieser Katalogeintrag und seine Kontextverknüpfungen werden entfernt.',
    'projectDeleted': 'Projekt gelöscht',
    'chapterDeleted': 'Kapitel gelöscht',
    'sceneDeleted': 'Szene gelöscht',
    'catalogItemDeleted': 'Katalogeintrag gelöscht',
    'untitledProject': 'Unbenanntes Projekt',
    'localOnly': 'Lokal',
    'projectCreated': 'Projekt angelegt',
    'newScene': 'Neue Szene',
    'newChapter': 'Neues Kapitel',
    'chapter': 'Kapitel',
    'chapterTitle': 'Kapiteltitel',
    'untitledChapter': 'Unbenanntes Kapitel',
    'chapterCreated': 'Kapitel angelegt',
    'noChapter': 'Ohne Kapitel',
    'sceneTitle': 'Szenentitel',
    'untitledScene': 'Unbenannte Szene',
    'sceneCreated': 'Szene angelegt',
    'noScenesTitle': 'Noch keine Szenen',
    'noScenesBody':
        'Lege eine Szene an, um Manuskript, Ziel, Konflikt und Ausgang zu planen.',
    'manuscript': 'Manuskript',
    'saveScene': 'Szene speichern',
    'sceneSaved': 'Szene gespeichert',
    'selectScene': 'Wähle eine Szene aus',
    'words': 'Wörter',
    'characterCount': 'Zeichen',
    'targetProgress': 'Wortziel',
    'focusMode': 'Fokusmodus',
    'exitFocusMode': 'Fokusmodus verlassen',
    'searchReplace': 'Suchen und ersetzen',
    'findText': 'Suchen',
    'replaceWith': 'Ersetzen durch',
    'matches': 'Treffer',
    'nextMatch': 'Nächster Treffer',
    'replaceNext': 'Nächstes ersetzen',
    'replaceAll': 'Alle ersetzen',
    'autosaveSaved': 'Gespeichert',
    'autosavePending': 'Ungespeichert',
    'autosaveSaving': 'Speichert...',
    'autosaveError': 'Speichern fehlgeschlagen',
    'sceneInspector': 'Szenen-Inspektor',
    'summary': 'Zusammenfassung',
    'goal': 'Ziel',
    'conflict': 'Konflikt',
    'outcome': 'Ausgang',
    'status': 'Status',
    'wordTarget': 'Wortziel',
    'catalog': 'Katalog',
    'name': 'Name',
    'newCharacter': 'Neue Figur',
    'newLocation': 'Neuer Ort',
    'newObject': 'Neues Objekt',
    'newCatalogItem': 'Neuer Eintrag',
    'editCatalogItem': 'Eintrag bearbeiten',
    'saveCatalogItem': 'Eintrag speichern',
    'untitledCharacter': 'Unbenannte Figur',
    'untitledLocation': 'Unbenannter Ort',
    'untitledObject': 'Unbenanntes Objekt',
    'untitledCatalogItem': 'Unbenannter Eintrag',
    'catalogItemCreated': 'Katalogeintrag angelegt',
    'catalogItemSaved': 'Katalogeintrag gespeichert',
    'noCharactersTitle': 'Noch keine Figuren',
    'noLocationsTitle': 'Noch keine Orte',
    'noObjectsTitle': 'Noch keine Objekte',
    'noCatalogItemsTitle': 'Noch keine Einträge',
    'catalogEmptyBody':
        'Lege Profile an und nutze sie als Kontext für Szenen, Analyse und KI-Vorschläge.',
    'noSummary': 'Keine Zusammenfassung',
    'sceneContext': 'Szenenkontext',
    'sceneContextEmpty':
        'Lege Figuren, Orte oder Objekte an, um sie mit dieser Szene zu verknüpfen.',
    'relationships': 'Verknüpfungen',
    'openSuggestions': 'Offene Vorschläge',
    'metricEvents': 'Lokale Events',
    'todaySaves': 'Speicherungen heute',
    'aiUses': 'KI-Nutzung',
    'recentMetrics': 'Letzte lokale Ereignisse',
    'noMetricsYet': 'Noch keine lokalen Metriken für dieses Projekt.',
    'recentScenes': 'Aktuelle Szenen',
    'sceneBoard': 'Szenenboard',
    'structureCockpit': 'Struktur-Cockpit',
    'planningGaps': 'Planungslücken',
    'unassignedScenes': 'Ohne Kapitel',
    'timeline': 'Timeline',
    'unscheduled': 'Ohne Datum',
    'statusSpread': 'Statusverteilung',
    'datedScenes': 'Datierte Szenen',
    'chapterOverview': 'Kapitelüberblick',
    'structureInspector': 'Struktur-Inspektor',
    'authorStructureCockpit': 'Autoren-Cockpit',
    'authorStructureCockpitBody':
        'Szenenfluss, offene Konflikte, Entitäten und Muster im aktuellen Projekt.',
    'structureComplete': 'Planung vollständig',
    'missing': 'Fehlt',
    'openScene': 'Szene öffnen',
    'noPlanningGaps': 'Keine offenen Planungslücken',
    'openConflicts': 'Offene Konflikte',
    'noOpenConflicts': 'Keine offenen Konflikte',
    'noUnscheduledScenes': 'Alle Szenen haben ein Datum',
    'noTimelineScenes': 'Noch keine datierten Szenen',
    'entityWeb': 'Entitätsnetz',
    'motifTracker': 'Motiv-Tracker',
    'noMotifsYet': 'Noch keine Muster aus Szenentyp, Ton oder Status.',
    'relationshipMap': 'Beziehungskarte',
    'noRelationshipsYet': 'Noch keine Beziehungen verknüpft.',
    'sceneType': 'Szenentyp',
    'emotionalTone': 'Ton',
    'storyAnalysis': 'Storyline & Analyse',
    'storylineHealth': 'Storyline-Prüfung',
    'chapterBalance': 'Kapitelbalance',
    'catalogPresence': 'Präsenzmatrix',
    'openPlanningGaps': 'Offene Planungslücken',
    'scenesWithoutPov': 'Szenen ohne Perspektive',
    'scenesWithoutDate': 'Szenen ohne Datum',
    'detachedCatalogItems': 'Einträge ohne Auftritt',
    'missingStructure': 'Ziel, Konflikt oder Ausgang fehlt',
    'noAnalysisIssues': 'Keine akuten Strukturhinweise.',
    'noAppearances': 'Keine Auftritte',
    'appearances': 'Auftritte',
    'linkedScenes': 'Verknüpfte Szenen',
    'wordsPerChapter': 'Wörter pro Kapitel',
    'structureActions': 'Strukturaktionen',
    'moveSceneUp': 'Szene nach oben',
    'moveSceneDown': 'Szene nach unten',
    'moveToChapter': 'In Kapitel verschieben',
    'moveToNoChapter': 'Ohne Kapitel',
    'aiNeedsScene':
        'Lege zuerst eine Szene an, bevor KI-Vorschläge erzeugt werden.',
    'aiContext': 'Kontext',
    'aiPrompt': 'Auftrag an die KI',
    'defaultAiPrompt':
        'Prüfe diese Szene und schlage strukturierende Fragen vor.',
    'requestSceneIdeas': 'Szenenideen',
    'requestStructure': 'Ziel/Konflikt/Ausgang',
    'moreAiChecks': 'Weitere Prüfungen',
    'submitAiPrompt': 'Auftrag senden',
    'aiPromptSubmitHint': 'Strg+Enter sendet den Auftrag',
    'aiApiKeyMissing':
        'Für diesen Provider ist ein API-Key nötig. Speichere ihn unter Einstellungen > Provider-Konfiguration.',
    'aiRequestInProgress': 'Provider-Anfrage läuft...',
    'aiRequestFailed': 'Provider-Anfrage fehlgeschlagen',
    'aiSuggestionCreated': 'KI-Vorschlag gespeichert',
    'aiMockProviderActive':
        'Mock / lokal ist aktiv - Antworten sind Demo-Platzhalter. Speichere OpenRouter oder einen anderen Provider in den Einstellungen.',
    'aiTaskCustomScenePrompt': 'Eigener KI-Auftrag',
    'aiTaskCharacterProfile': 'Figurenprofil',
    'aiTaskConsistencyCheck': 'Konsistenzprüfung',
    'aiTaskTimelineCheck': 'Timeline-Prüfung',
    'aiTaskStorylineVariants': 'Storyline-Varianten',
    'aiTaskBlurbVariants': 'Klappentext-Varianten',
    'aiTaskStyleAnalysis': 'Stilanalyse',
    'aiTaskAuthorQuestions': 'Autorenfragen',
    'aiTaskResearchStructuring': 'Recherche strukturieren',
    'aiTaskPlotGapReview': 'Plot-Lücken prüfen',
    'aiTaskDialogueIntentAnalysis': 'Dialogabsicht analysieren',
    'suggestions': 'Vorschläge',
    'noSuggestions': 'Noch keine Vorschläge',
    'notes': 'Notizen',
    'noNotes': 'Noch keine Notizen',
    'notesCockpit': 'Notizen-Cockpit',
    'newNote': 'Neue Notiz',
    'editNote': 'Notiz bearbeiten',
    'untitledNote': 'Unbenannte Notiz',
    'noteTitle': 'Titel',
    'noteBody': 'Notiz',
    'noteTarget': 'Ziel',
    'targetProject': 'Projekt allgemein',
    'searchNotes': 'Notizen suchen',
    'allNotes': 'Alle',
    'projectNotes': 'Projekt',
    'sceneNotes': 'Szenen',
    'catalogNotes': 'Katalog',
    'manualNotes': 'Manuell',
    'aiNotes': 'KI',
    'manualNote': 'Manuelle Notiz',
    'aiNote': 'KI-Notiz',
    'noNotesForFilter': 'Keine passenden Notizen',
    'noNoteSelectedTitle': 'Keine Notiz ausgewählt',
    'noNoteSelectedBody':
        'Lege eine Notiz an oder wähle links einen Eintrag aus.',
    'openLinkedScene': 'Verknüpfte Szene öffnen',
    'saveNote': 'Notiz speichern',
    'noteCreated': 'Notiz angelegt',
    'noteSaved': 'Notiz gespeichert',
    'noteDeleted': 'Notiz gelöscht',
    'aiResponse': 'Antwort',
    'sentPrompt': 'Gesendeter Prompt',
    'suggestionPending': 'offen',
    'suggestionAccepted': 'angenommen',
    'suggestionRejected': 'abgelehnt',
    'suggestionConverted': 'als Notiz gesichert',
    'suggestionAcceptedFeedback': 'Vorschlag angenommen',
    'suggestionAppliedFeedback': 'Vorschlag auf Szenenplanung angewendet',
    'suggestionAcceptedNoPatchFeedback':
        'Vorschlag angenommen, keine Planungsfelder geändert',
    'suggestionDeletedFeedback': 'Vorschlag gelöscht',
    'suggestionConvertedFeedback': 'Notiz aus Vorschlag erstellt',
    'applyPreview': 'Änderungsvorschau',
    'noApplyPreview':
        'Keine übernehmbaren Szenenfelder erkannt. Annehmen markiert den Vorschlag nur als geprüft.',
    'accept': 'Annehmen',
    'reject': 'Ablehnen',
    'convertToNote': 'Als Notiz markieren',
    'exportPreview': 'Exportvorschau',
    'copyExport': 'Export kopieren',
    'downloadExport': 'Export herunterladen',
    'exportCopied': 'Export in die Zwischenablage kopiert',
    'exportDownloaded': 'Export heruntergeladen',
    'syncCheckpoint': 'Sync-Checkpoint',
    'syncCheckpointBody':
        'Erzeugt ein vollständiges, lokales Sync-Paket für manuelle Ablage, WebDAV oder spätere Cloud-Adapter.',
    'copySyncCheckpoint': 'Sync-Checkpoint kopieren',
    'syncCheckpointCopied': 'Sync-Checkpoint in die Zwischenablage kopiert',
    'lastSyncCheckpoint': 'Letzter Checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Paketgröße',
    'syncPayloadDetected': 'Sync-Paket erkannt',
    'syncAdapter': 'Sync-Adapter',
    'syncAdapterHint':
        'Lokale Nutzung bleibt unabhängig; Cloud-Sync ist nur ein optionaler Adapter.',
    'importArchive': 'Projektarchiv importieren',
    'archiveSchema': 'Archivschema',
    'archivePreviewInvalid': 'Archivvorschau nicht möglich',
    'pasteArchiveJson': 'Writeler-JSON hier einfügen',
    'importProject': 'Projekt importieren',
    'importComplete': 'Projektarchiv importiert',
    'format': 'Format',
    'includeSceneTitles': 'Szenentitel einschließen',
    'includeMetadata': 'Metadaten einschließen',
    'nothingToExport': 'Noch nichts zu exportieren',
    'selectProject': 'Wähle ein Projekt aus',
    'aiEnabled': 'KI-Unterstützung',
    'cloudSyncEnabled': 'Cloud-Sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider-Konfiguration',
    'providerKind': 'Provider-Typ',
    'providerEnabled': 'Provider aktiv',
    'providerName': 'Providername',
    'modelName': 'Modellname',
    'baseUrl': 'Base-URL',
    'apiKeyRef': 'API-Key',
    'apiKeyWebWarning':
        'Wird getrennt von der Provider-Konfiguration sicher lokal gespeichert.',
    'apiKeyStoredHint':
        'API-Key ist sicher gespeichert. Leer lassen, um ihn beizubehalten.',
    'deleteApiKey': 'API-Key entfernen',
    'apiKeyDeleted': 'API-Key entfernt',
    'saveProviderConfig': 'Provider speichern',
    'providerConfigSaved': 'Provider-Konfiguration gespeichert',
    'activeProvider': 'Aktiver Provider',
    'providerNameFallback': 'Lokaler Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  static const _en = {
    'appTitle': 'Writeler',
    'dashboard': 'Dashboard',
    'projects': 'Projects',
    'project': 'Project',
    'editor': 'Editor',
    'scenes': 'Scenes',
    'scene': 'Scene',
    'chapters': 'Chapters',
    'characters': 'Characters',
    'character': 'Character',
    'characterCount': 'Characters',
    'locations': 'Locations',
    'location': 'Location',
    'objects': 'Objects',
    'object': 'Object',
    'analysis': 'Analysis',
    'aiWorkshop': 'AI Workshop',
    'exports': 'Export',
    'settings': 'Settings',
    'designSettings': 'Design',
    'designSettingsBody':
        'Choose the working mood for the interface, brand, and focus surfaces.',
    'designThemePaper': 'Light',
    'designThemeDusk': 'Dark',
    'designThemeSapphire': 'Sapphire',
    'designThemeSage': 'Sage',
    'designThemeCopper': 'Copper',
    'designThemeInk': 'Ink',
    'privacySettings': 'Project & privacy',
    'privacySettingsBody':
        'Controls how this project uses AI and optional sync.',
    'providerSettingsBody':
        'Configure provider, model, and API key for AI features.',
    'emptyTitle': 'No project open',
    'emptyBody':
        'Create a local writing project and organize it into chapters, scenes, and notes.',
    'dashboardBody':
        'Project status, open structure points, and next work steps in one place.',
    'openEditor': 'Open editor',
    'projectPulse': 'Project pulse',
    'nextActions': 'Next steps',
    'nextActionsBody':
        'Direct routes to the areas that currently need attention.',
    'continueWriting': 'Continue writing',
    'reviewStructure': 'Review structure',
    'reviewSuggestions': 'Review AI suggestions',
    'reviewNotes': 'Review notes',
    'nextSceneWithoutText': 'Next scene without text',
    'mostUrgentPlanningGap': 'Most urgent planning gap',
    'latestOpenAiResponse': 'Latest open AI response',
    'noteWithoutTarget': 'Note without target',
    'noDashboardActions': 'No urgent next steps.',
    'structureFocus': 'Structure status',
    'structureFocusBody':
        'Planning, assignment, and catalog links for the current project.',
    'emptyDraftScenes': 'Scenes without manuscript',
    'recentScenesBody':
        'Recently edited scenes with word count and planning status.',
    'noRecentScenes': 'No scenes in this project yet.',
    'activityStream': 'Activity',
    'activityStreamBody': 'Local events from writing, AI, and export.',
    'noActivityYet': 'No activity for this project yet.',
    'dashboardSignals': 'Signals',
    'dashboardSignalsBody':
        'Short status for AI, notes, and today writing work.',
    'aiQueue': 'AI queue',
    'notesQueue': 'Notes',
    'newProject': 'New Project',
    'projectTitle': 'Project title',
    'create': 'Create',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'deletePermanently': 'Delete permanently',
    'deleteProject': 'Delete project',
    'deleteChapter': 'Delete chapter',
    'deleteScene': 'Delete scene',
    'deleteCatalogItem': 'Delete entry',
    'deleteProjectBody':
        'This project and all local chapters, scenes, catalog entries, suggestions, and metrics will be removed.',
    'deleteChapterBody':
        'The chapter will be removed. Its scenes stay available and move to no chapter.',
    'deleteSceneBody': 'This scene and its context links will be removed.',
    'deleteCatalogItemBody':
        'This catalog entry and its context links will be removed.',
    'projectDeleted': 'Project deleted',
    'chapterDeleted': 'Chapter deleted',
    'sceneDeleted': 'Scene deleted',
    'catalogItemDeleted': 'Catalog item deleted',
    'untitledProject': 'Untitled Project',
    'localOnly': 'Local',
    'projectCreated': 'Project created',
    'newScene': 'New Scene',
    'newChapter': 'New Chapter',
    'chapter': 'Chapter',
    'chapterTitle': 'Chapter title',
    'untitledChapter': 'Untitled Chapter',
    'chapterCreated': 'Chapter created',
    'noChapter': 'No chapter',
    'sceneTitle': 'Scene title',
    'untitledScene': 'Untitled Scene',
    'sceneCreated': 'Scene created',
    'noScenesTitle': 'No scenes yet',
    'noScenesBody':
        'Create a scene to plan manuscript, goal, conflict, and outcome.',
    'manuscript': 'Manuscript',
    'saveScene': 'Save Scene',
    'sceneSaved': 'Scene saved',
    'selectScene': 'Select a scene',
    'words': 'words',
    'targetProgress': 'Word target',
    'focusMode': 'Focus mode',
    'exitFocusMode': 'Exit focus mode',
    'searchReplace': 'Find and replace',
    'findText': 'Find',
    'replaceWith': 'Replace with',
    'matches': 'Matches',
    'nextMatch': 'Next match',
    'replaceNext': 'Replace next',
    'replaceAll': 'Replace all',
    'autosaveSaved': 'Saved',
    'autosavePending': 'Unsaved',
    'autosaveSaving': 'Saving...',
    'autosaveError': 'Save failed',
    'sceneInspector': 'Scene inspector',
    'summary': 'Summary',
    'goal': 'Goal',
    'conflict': 'Conflict',
    'outcome': 'Outcome',
    'status': 'Status',
    'wordTarget': 'Word target',
    'catalog': 'Catalog',
    'name': 'Name',
    'newCharacter': 'New Character',
    'newLocation': 'New Location',
    'newObject': 'New Object',
    'newCatalogItem': 'New Entry',
    'editCatalogItem': 'Edit entry',
    'saveCatalogItem': 'Save entry',
    'untitledCharacter': 'Untitled Character',
    'untitledLocation': 'Untitled Location',
    'untitledObject': 'Untitled Object',
    'untitledCatalogItem': 'Untitled Entry',
    'catalogItemCreated': 'Catalog item created',
    'catalogItemSaved': 'Catalog item saved',
    'noCharactersTitle': 'No characters yet',
    'noLocationsTitle': 'No locations yet',
    'noObjectsTitle': 'No objects yet',
    'noCatalogItemsTitle': 'No entries yet',
    'catalogEmptyBody':
        'Create profiles and use them as context for scenes, analysis, and AI suggestions.',
    'noSummary': 'No summary',
    'sceneContext': 'Scene context',
    'sceneContextEmpty':
        'Create characters, locations, or objects to link them with this scene.',
    'relationships': 'Relationships',
    'openSuggestions': 'Open suggestions',
    'metricEvents': 'Local events',
    'todaySaves': 'Saves today',
    'aiUses': 'AI usage',
    'recentMetrics': 'Recent local events',
    'noMetricsYet': 'No local metrics for this project yet.',
    'recentScenes': 'Recent scenes',
    'sceneBoard': 'Scene board',
    'structureCockpit': 'Structure cockpit',
    'planningGaps': 'Planning gaps',
    'unassignedScenes': 'No chapter',
    'timeline': 'Timeline',
    'unscheduled': 'Unscheduled',
    'statusSpread': 'Status spread',
    'datedScenes': 'Dated scenes',
    'chapterOverview': 'Chapter overview',
    'structureInspector': 'Structure inspector',
    'authorStructureCockpit': 'Author cockpit',
    'authorStructureCockpitBody':
        'Scene flow, open conflicts, entities, and patterns in the current project.',
    'structureComplete': 'Planning complete',
    'missing': 'Missing',
    'openScene': 'Open scene',
    'noPlanningGaps': 'No open planning gaps',
    'openConflicts': 'Open conflicts',
    'noOpenConflicts': 'No open conflicts',
    'noUnscheduledScenes': 'All scenes have a date',
    'noTimelineScenes': 'No dated scenes yet',
    'entityWeb': 'Entity web',
    'motifTracker': 'Motif tracker',
    'noMotifsYet': 'No patterns from scene type, tone, or status yet.',
    'relationshipMap': 'Relationship map',
    'noRelationshipsYet': 'No relationships linked yet.',
    'sceneType': 'Scene type',
    'emotionalTone': 'Tone',
    'storyAnalysis': 'Storyline & Analysis',
    'storylineHealth': 'Storyline health',
    'chapterBalance': 'Chapter balance',
    'catalogPresence': 'Presence matrix',
    'openPlanningGaps': 'Open planning gaps',
    'scenesWithoutPov': 'Scenes without POV',
    'scenesWithoutDate': 'Scenes without date',
    'detachedCatalogItems': 'Entries without appearance',
    'missingStructure': 'Goal, conflict, or outcome is missing',
    'noAnalysisIssues': 'No immediate structure notes.',
    'noAppearances': 'No appearances',
    'appearances': 'Appearances',
    'linkedScenes': 'Linked scenes',
    'wordsPerChapter': 'Words per chapter',
    'structureActions': 'Structure actions',
    'moveSceneUp': 'Move scene up',
    'moveSceneDown': 'Move scene down',
    'moveToChapter': 'Move to chapter',
    'moveToNoChapter': 'No chapter',
    'aiNeedsScene': 'Create a scene before requesting AI suggestions.',
    'aiContext': 'Context',
    'aiPrompt': 'AI task',
    'defaultAiPrompt': 'Review this scene and suggest structuring questions.',
    'requestSceneIdeas': 'Scene ideas',
    'requestStructure': 'Goal/conflict/outcome',
    'moreAiChecks': 'More checks',
    'submitAiPrompt': 'Send task',
    'aiPromptSubmitHint': 'Ctrl+Enter sends the task',
    'aiApiKeyMissing':
        'This provider needs an API key. Save it under Settings > Provider configuration.',
    'aiRequestInProgress': 'Provider request in progress...',
    'aiRequestFailed': 'Provider request failed',
    'aiSuggestionCreated': 'AI suggestion saved',
    'aiMockProviderActive':
        'Mock / local is active - responses are demo placeholders. Save OpenRouter or another provider in Settings.',
    'aiTaskCustomScenePrompt': 'Custom AI task',
    'aiTaskCharacterProfile': 'Character profile',
    'aiTaskConsistencyCheck': 'Consistency check',
    'aiTaskTimelineCheck': 'Timeline check',
    'aiTaskStorylineVariants': 'Storyline variants',
    'aiTaskBlurbVariants': 'Blurb variants',
    'aiTaskStyleAnalysis': 'Style analysis',
    'aiTaskAuthorQuestions': 'Author questions',
    'aiTaskResearchStructuring': 'Research structuring',
    'aiTaskPlotGapReview': 'Plot gap review',
    'aiTaskDialogueIntentAnalysis': 'Dialogue intent analysis',
    'suggestions': 'Suggestions',
    'noSuggestions': 'No suggestions yet',
    'notes': 'Notes',
    'noNotes': 'No notes yet',
    'notesCockpit': 'Notes cockpit',
    'newNote': 'New note',
    'editNote': 'Edit note',
    'untitledNote': 'Untitled note',
    'noteTitle': 'Title',
    'noteBody': 'Note',
    'noteTarget': 'Target',
    'targetProject': 'Project-wide',
    'searchNotes': 'Search notes',
    'allNotes': 'All',
    'projectNotes': 'Project',
    'sceneNotes': 'Scenes',
    'catalogNotes': 'Catalog',
    'manualNotes': 'Manual',
    'aiNotes': 'AI',
    'manualNote': 'Manual note',
    'aiNote': 'AI note',
    'noNotesForFilter': 'No matching notes',
    'noNoteSelectedTitle': 'No note selected',
    'noNoteSelectedBody': 'Create a note or select an item on the left.',
    'openLinkedScene': 'Open linked scene',
    'saveNote': 'Save note',
    'noteCreated': 'Note created',
    'noteSaved': 'Note saved',
    'noteDeleted': 'Note deleted',
    'aiResponse': 'Response',
    'sentPrompt': 'Sent prompt',
    'suggestionPending': 'pending',
    'suggestionAccepted': 'accepted',
    'suggestionRejected': 'rejected',
    'suggestionConverted': 'saved as note',
    'suggestionAcceptedFeedback': 'Suggestion accepted',
    'suggestionAppliedFeedback': 'Suggestion applied to scene planning',
    'suggestionAcceptedNoPatchFeedback':
        'Suggestion accepted, no planning fields changed',
    'suggestionDeletedFeedback': 'Suggestion deleted',
    'suggestionConvertedFeedback': 'Note created from suggestion',
    'applyPreview': 'Apply preview',
    'noApplyPreview':
        'No applicable scene fields detected. Accepting only marks the suggestion as reviewed.',
    'accept': 'Accept',
    'reject': 'Reject',
    'convertToNote': 'Mark as note',
    'exportPreview': 'Export preview',
    'copyExport': 'Copy export',
    'downloadExport': 'Download export',
    'exportCopied': 'Export copied to clipboard',
    'exportDownloaded': 'Export downloaded',
    'syncCheckpoint': 'Sync checkpoint',
    'syncCheckpointBody':
        'Creates a complete local sync package for manual storage, WebDAV, or future cloud adapters.',
    'copySyncCheckpoint': 'Copy sync checkpoint',
    'syncCheckpointCopied': 'Sync checkpoint copied to clipboard',
    'lastSyncCheckpoint': 'Last checkpoint',
    'syncFingerprint': 'Fingerprint',
    'syncPayloadSize': 'Payload size',
    'syncPayloadDetected': 'Sync package detected',
    'syncAdapter': 'Sync adapter',
    'syncAdapterHint':
        'Local use remains independent; cloud sync is only an optional adapter.',
    'importArchive': 'Import project archive',
    'archiveSchema': 'Archive schema',
    'archivePreviewInvalid': 'Archive preview unavailable',
    'pasteArchiveJson': 'Paste Writeler JSON here',
    'importProject': 'Import project',
    'importComplete': 'Project archive imported',
    'format': 'Format',
    'includeSceneTitles': 'Include scene titles',
    'includeMetadata': 'Include metadata',
    'nothingToExport': 'Nothing to export yet',
    'selectProject': 'Select a project',
    'aiEnabled': 'AI assistance',
    'cloudSyncEnabled': 'Cloud sync',
    'noAiNoCloud': 'No AI / No Cloud',
    'providerConfig': 'Provider configuration',
    'providerKind': 'Provider type',
    'providerEnabled': 'Provider enabled',
    'providerName': 'Provider name',
    'modelName': 'Model name',
    'baseUrl': 'Base URL',
    'apiKeyRef': 'API key',
    'apiKeyWebWarning':
        'Stored locally in secure storage, separate from provider configuration.',
    'apiKeyStoredHint': 'API key is securely stored. Leave blank to keep it.',
    'deleteApiKey': 'Delete API key',
    'apiKeyDeleted': 'API key deleted',
    'saveProviderConfig': 'Save provider',
    'providerConfigSaved': 'Provider configuration saved',
    'activeProvider': 'Active provider',
    'providerNameFallback': 'Local Provider',
    'modelNameFallback': 'mock-structure-v1',
  };

  String t(String key) {
    final table = languageCode == 'de' ? _de : _en;
    return table[key] ?? _en[key] ?? key;
  }
}
